### PR TITLE
Removed dedicated versioneer

### PR DESCRIPTION
**Pull request by antnieszka**

### CODE REVIEW

**Comment by ant6** [comment]
(Rebase in progress)

**Comment by antnieszka** [comment]
@grzanka another one to review - now everything should pass

**Comment by antnieszka** [comment]
Closes #103

**Comment by grzanka** [comment]
I still see problems with Travis Python3.2
https://travis-ci.org/DataMedSci/beprof/jobs/180974826

May it be new release of setuptools ?
https://pypi.python.org/pypi/setuptools

Check when setuptools-30.1.0 was released.
Did previous version had support for 3.2 and in current its dropped ?

**Comment by antnieszka** [comment]
New version was uploaded to pypi on 2016-12-03. I'll investigate further.

**Comment by antnieszka** [comment]
@grzanka even worse:
```
01 Dec 2016

    #864: Drop support for Python 3.2. Systems requiring Python 3.2 support must use ‘setuptools < 30’.
```

**Comment by grzanka** [comment]
There is a way to fix it, check this one:

https://github.com/DataMedSci/beprof/blob/master/.travis/install_linux.sh#L14
`pip install --upgrade virtualenv$VENVVER pip$PIPVER setuptools tox wheel`

and
https://github.com/DataMedSci/beprof/blob/master/.travis.yml#L18
`env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0"`

Add new variable STVER="<30.0.0" where necessary.

**Comment by grzanka** [comment]
Can you also fix https://github.com/pytrip/pytrip/issues/194 and https://github.com/DataMedSci/pymchelper/issues/146 if this patch will work ?

**Comment by antnieszka** [comment]
@grzanka It works: https://travis-ci.org/DataMedSci/beprof/jobs/180979843

**Comment by antnieszka** [comment]
Hmm, but still OSX may fail...

**Comment by grzanka** [comment]
No, OSX works well, I'll merge it. Please submit similar fix to pymchelper and pytrip projects.

**Pull request merged**
