### PR TITLE
Added setuptools mention to readme #70

### PR DESCRIPTION
**Pull request by antnieszka**
@grzanka is this what You had in mind?

### CODE REVIEW

**Comment by grzanka** [comment]
Wercker is complaining now. Could you first create PR with dummy wercker config ?

**Comment by grzanka** [comment]
And yes - I mean't exactly this change to README.rst

**Comment by antnieszka** [comment]
Ok, I'll add dummy config.

**Comment by grzanka** [comment]
@ant6 please rebase

**Comment by antnieszka** [comment]
Done.

**Pull request merged**
