### PR TITLE
Fixed syntax error #47

### PR DESCRIPTION
**Pull request by antnieszka**
This should fix failing builds for Python 2.7

### CODE REVIEW

**Comment by antnieszka** [comment]
@grzanka please review

**Comment by antnieszka** [comment]
Looks like only peps are failing now. https://travis-ci.org/DataMedSci/beprof/builds/135559943

**Comment by grzanka** [comment]
Looks OK

**Comment by grzanka** [comment]
Closes #47

**Comment by grzanka** [comment]
Close #47

**Pull request merged**
