### PR TITLE
#16 fixing

### LINKED ISSUE #16: rebinning method is removing all metadata
See following code:

```
>>> from beprof import curve
>>> c1 = curve.Curve( [[0,0],[1,1]], generator="sin")
>>> c2 = c1.rebinned()
>>> print(c1)
shape: (2, 2)
X : [0.000,1.000]
Y : [0.000000,1.000000]
Metadata : {'generator': 'sin'}
>>> print(c2)
shape: (11, 2)
X : [0.000,1.000]
Y : [0.000000,1.000000]
Metadata : {}
```

### PR DESCRIPTION
**Pull request by matkrak**
Fixed issue of removing metadata by rebinning methods (change_domain method more accurately). This one probably closes #16

### CODE REVIEW

**Comment by matkrak** [comment]
This Merge pull request bothers me. Am I working on up-to-date version of repository, because I am pretty sure I am.

**Comment by grzanka** [comment]
Was it a question ?

**Comment by matkrak** [comment]
Yes just missing question mark. Did I merge the repositories correctly?

**Comment by grzanka** [comment]
At first glance - yes.

**Comment by matkrak** [comment]
So does this issue require futher changes or I should consider it done?

**Comment by grzanka** [comment]
Still doesn't work:

```
>>> from beprof import curve
>>> c1 = curve.Curve( [[0,0],[1,1]], generator="sin")
>>> print(c1)
shape: (2, 2)
X : [0.000,1.000]
Y : [0.000000,1.000000]
Metadata : {'generator': 'sin'}
>>> c2 = c1.rebinned()
>>> print(c2)
shape: (11, 2)
X : [0.000,1.000]
Y : [0.000000,1.000000]
Metadata : {'metadata': {'generator': 'sin'}}
```

c1 metadata is different from c2 metadata.

**Comment by matkrak** [comment]
Now it does for rebinning methods. Another thing is slicing and `view()` method, but it is in issue #18

**Pull request merged**
